/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.plessmann.airdata.views;

import com.plessmann.airdata.Constants;
import com.plessmann.airdata.controllers.DataLoader;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Plesse
 */
public class DataSource extends javax.swing.JFrame {

    /**
     * Creates new form DataSource
     */
    public DataSource() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        selectedCountryLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectedAirportLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectedRunwayLabel = new javax.swing.JLabel();
        selectCountryButton = new javax.swing.JButton();
        selectAirportButton = new javax.swing.JButton();
        selectRunwayButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setText(Constants.COUNTRIES);

        jLabel3.setText(Constants.AIRPORTS);

        jLabel5.setText(Constants.RUNWAYS);

        selectCountryButton.setText(Constants.SELECT);
        selectCountryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCountryButtonActionPerformed(evt);
            }
        });

        selectAirportButton.setText(Constants.SELECT);
        selectAirportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAirportButtonActionPerformed(evt);
            }
        });

        selectRunwayButton.setText(Constants.SELECT);
        selectRunwayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRunwayButtonActionPerformed(evt);
            }
        });

        closeButton.setText(Constants.CLOSE);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedCountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectedAirportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectedRunwayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectRunwayButton)
                    .addComponent(selectCountryButton)
                    .addComponent(selectAirportButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCountryButton)
                    .addComponent(selectedCountryLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAirportButton)
                    .addComponent(jLabel3)
                    .addComponent(selectedAirportLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectRunwayButton)
                    .addComponent(jLabel5)
                    .addComponent(selectedRunwayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        DataLoader dataLoader = new DataLoader();
        dataLoader.load(countries, airports, runways);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void selectCountryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCountryButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            countries = fileChooser.getSelectedFile();
            selectedCountryLabel.setText(countries.getName());
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_selectCountryButtonActionPerformed

    private void selectAirportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAirportButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            airports = fileChooser.getSelectedFile();
            selectedAirportLabel.setText(airports.getName());
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_selectAirportButtonActionPerformed

    private void selectRunwayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRunwayButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            runways = fileChooser.getSelectedFile();
            selectedRunwayLabel.setText(runways.getName());
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_selectRunwayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DataSource().setVisible(true);
        });
    }

    private File countries;
    private File airports;
    private File runways;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton selectAirportButton;
    private javax.swing.JButton selectCountryButton;
    private javax.swing.JButton selectRunwayButton;
    private javax.swing.JLabel selectedAirportLabel;
    private javax.swing.JLabel selectedCountryLabel;
    private javax.swing.JLabel selectedRunwayLabel;
    // End of variables declaration//GEN-END:variables
}
